# If the name bothers you, you can simply: ln -s compose.portainer.yml docker-compose.yml 
version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443  # We want https for SSL, not 9000:9000, which yields http.
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  portainer_data:
