# version: "3" # disable the vesrion for warmings during launches on Ubuntu 24 Mininal on Oracle Cloud
               # WARN[0000] /opt/vyzed-portainer/vyzed-portainer.yml: 
               # the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443  # We want https for SSL, not 9000:9000, which yields http.
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  portainer_data:
